### ISSUE TITLE
Builds are unrealiable because of failing endpoints

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-stream-page#1058] opened 2016-05-11 14:47 UTC
It would be great if they weren't.

http://ft-stream-branch-2468.herokuapp.com/special-reports/MDEzZjdiOTAtYTFhNC00NzBjLTk2ZWMtMWFlOTZmZTM5Yzkz-U3BlY2lhbFJlcG9ydHM=/special-reports: bad status: 504
http://ft-stream-branch-2467.herokuapp.com/special-reports/MDEzZjdiOTAtYTFhNC00NzBjLTk2ZWMtMWFlOTZmZTM5Yzkz-U3BlY2lhbFJlcG9ydHM=/special-reports: bad status: 504
http://ft-stream-branch-2466.herokuapp.com/special-reports: bad status: 504
http://ft-stream-branch-2464.herokuapp.com/special-reports: bad status: 504

**Comment by i-like-robots** [comment] 2016-05-11 16:25
duplicate of #1032

**Comment by i-like-robots** [comment] 2016-05-11 16:25
duplicate of #1032

**Closed by i-like-robots** 2016-05-11 16:25 UTC
